# Generated by Django 4.0.3 on 2022-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_hotels_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
