# Generated by Django 4.0.3 on 2022-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='rating',
            field=models.CharField(default='', max_length=5),
        ),
    ]
