# Generated by Django 4.0.3 on 2022-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_hotels_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
    ]
