# Generated by Django 4.0.3 on 2022-04-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_profile_bio_profile_birth_date_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('AC', 'AC'), ('AC', 'NON-AC'), ('DELUXE', 'DELUXE'), ('KING', 'KING'), ('QUEEN', 'QUEEN')], max_length=15),
        ),
    ]
